get:
  tags:
    - Products
  summary: 商品詳細取得
  description: |
    指定された商品IDの詳細情報を取得します。
  operationId: getProductDetail
  security: []
  parameters:
    - name: productId
      in: path
      required: true
      description: 商品ID
      schema:
        type: string
        format: uuid
      example: "990e8400-e29b-41d4-a716-446655440000"
  responses:
    '200':
      description: 商品詳細取得成功
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/product.yaml#/Product'
    '404':
      $ref: '../../components/responses/common.yaml#/NotFound'
    '500':
      $ref: '../../components/responses/common.yaml#/InternalServerError'
