get:
  tags:
    - Products
  summary: 商品SKU一覧取得
  description: |
    指定された商品の利用可能なSKU（在庫単位）一覧を取得します。
  operationId: getProductSkus
  security: []
  parameters:
    - name: productId
      in: path
      required: true
      description: 商品ID
      schema:
        type: string
        format: uuid
      example: "990e8400-e29b-41d4-a716-446655440000"
  responses:
    '200':
      description: SKU一覧取得成功
      content:
        application/json:
          schema:
            type: object
            properties:
              skus:
                type: array
                items:
                  $ref: '../../components/schemas/product.yaml#/SKU'
    '404':
      $ref: '../../components/responses/common.yaml#/NotFound'
    '500':
      $ref: '../../components/responses/common.yaml#/InternalServerError'
